In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# 加载数据（兵王问题）
data = pd.read_csv('../Data/krkopt.data', header=None).values
# 特征数值化,将a-h转化为1-8
for i in [0,2,4]:
    data[:,i] = np.where(data[:,i]=='a', 1, data[:,i])
    data[:,i] = np.where(data[:,i]=='b', 2, data[:,i])
    data[:,i] = np.where(data[:,i]=='c', 3, data[:,i])
    data[:,i] = np.where(data[:,i]=='d', 4, data[:,i])
    data[:,i] = np.where(data[:,i]=='e', 5, data[:,i])
    data[:,i] = np.where(data[:,i]=='f', 6, data[:,i])
    data[:,i] = np.where(data[:,i]=='g', 7, data[:,i])
    data[:,i] = np.where(data[:,i]=='h', 8, data[:,i])
# 标签数值化,'draw'视为-1,其余视为1
data[:,-1] = np.where(data[:,-1]=='draw', 1.0, -1.0)

# 数据归一化
for i in range(6):
    data[:,i] = (data[:,i]-np.mean(data[:,i])) / np.std(data[:,i])
data = data.astype(np.float32)

# 划分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(data[:,:-1], data[:,-1], test_size=0.3, random_state=42)

In [29]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

################ 基于线性核的SVM #################
svm_linear = SVC(kernel='linear', C=1)
svm_linear.fit(X_train, y_train)
y_pred_svm_linear = svm_linear.predict(X_test)

# 计算准确率
accuracy_score_svm_linear = accuracy_score(y_test, y_pred_svm_linear)
# 计算混淆矩阵
cm_svm_linear = confusion_matrix(y_test, y_pred_svm_linear)
# 打印
print("基于线性核的SVM的准确率：", accuracy_score_svm_linear)
print("基于线性核的SVM的混淆矩阵：\n", cm_svm_linear)

################ 基于高斯核的SVM #################
svm_rbf = SVC(kernel='rbf', C=10.0, gamma=0.1)
svm_rbf.fit(X_train, y_train)
y_pred_svm_rbf = svm_rbf.predict(X_test)

# 计算准确率
accuracy_score_svm_rbf = accuracy_score(y_test, y_pred_svm_rbf)
# 计算混淆矩阵
cm_svm_rbf = confusion_matrix(y_test, y_pred_svm_rbf, labels=[-1.0,1.0])
# 打印
print("基于高斯核的SVM的准确率：", accuracy_score_svm_rbf)
print("基于高斯核的SVM的混淆矩阵：\n", cm_svm_rbf)



基于线性核的SVM的准确率： 0.9025781157181894
基于线性核的SVM的混淆矩阵：
 [[7597    0]
 [ 820    0]]
基于高斯核的SVM的准确率： 0.9960793631935368
基于高斯核的SVM的混淆矩阵：
 [[7570   27]
 [   6  814]]


In [43]:
################ 基于BP神经网络 #################
from sklearn.neural_network import MLPClassifier
BP = MLPClassifier(hidden_layer_sizes=(10,),
                   activation='logistic',
                   solver='adam',
                   learning_rate='invscaling',
                   max_iter=1000,
                   )
BP.fit(X_train, y_train)
y_pred_BP = BP.predict(X_test)

# 计算准确率
accuracy_score_BPNN = accuracy_score(y_test, y_pred_BP)
print("BPNN Accuracy: ", accuracy_score_BPNN)
# 计算混淆矩阵
confusion_matrix_BPNN = confusion_matrix(y_test, y_pred_BP)
print("BPNN Confusion Matrix: \n", confusion_matrix_BPNN)



BPNN Accuracy:  0.9939408340263752
BPNN Confusion Matrix: 
 [[7565   32]
 [  19  801]]


In [ ]:
################ 决策树 #################
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(criterion='entropy', max_depth=None)
tree.fit(X_train, y_train)
y_pred = tree.predict(X_test)

# 计算准确率
accuracy_score_tree = accuracy_score(y_test, y_pred)    
print("Accuracy score of Decision Tree:", accuracy_score_tree)
confusion_matrix_tree = confusion_matrix(y_test, y_pred)
print("Confusion matrix of Decision Tree:\n", confusion_matrix_tree)


Accuracy score of Decision Tree: 0.9963169775454438
Confusion matrix of Decision Tree:
 [[7583   14]
 [  17  803]]
